### ISSUE TITLE
Minor BugFixes

### ISSUE THREAD

**Issue by PersonalWeb** [mantisbt-plugins/mantweet#2]
While installing ManTweet on our local Mantis site, I discovered the following issues:
* The variable "$s_plugin_ManTweet_index",stored in the lang\strings_english.txt file did not appear to be in use. From its context, it appeared to be the text that should be used on the pages\index.php file for the plugin. Changing the line in this file:

    html_page_top1( lang_get( 'plugin_ManTweet_title' ) );

to: 

    html_page_top1( lang_get( 'plugin_ManTweet_index' ) );

seemed to be the way to resolve this issue.

* When using it as a "local" developer created feed, the posts were not being entered into the database. Mantis kept returning an error. By going to the mantweet_api.php file and changing the line:

    $t_query = "INSERT INTO $t_updates_table ( author_id, status, date_submitted, date_updated ) VALUES (" . db_param( 0 ) . ", " . db_param( 1 ) . ", '" . mantweet_db_now() . "', '" . mantweet_db_now() . "')";

to the conditional:

    if ( plugin_config_get( 'tweets_source' ) == 'local' ) {

        $t_query = "INSERT INTO $t_updates_table ( author_id, status, date_submitted, date_updated ) VALUES (" . db_param( 0 ) . ", " . db_param( 1 ) . ", " . mantweet_db_now() . ", " . mantweet_db_now() . ")";	

    } else {

        $t_query = "INSERT INTO $t_updates_table ( author_id, status, date_submitted, date_updated ) VALUES (" . db_param( 0 ) . ", " . db_param( 1 ) . ", '" . mantweet_db_now() . "', '" . mantweet_db_now() . "')";

    }	

resolved this issue.

**Comment by luzpaz** [comment]
I'm pondering on using mantweet...is this issue still relevant?

**Comment by dregad** [comment]
- 1st bullet fixed in 380639af2bb33232dee8178aabcd7b559fb51253
- 2nd issue 583547f1385b828273fd4843c1d9d2e9897892dd
