### ISSUE TITLE
Problem with local version

### ISSUE THREAD

**Issue by ducemmanuel** [mantisbt-plugins/mantweet#4]
Hello,
 
I installed the ManTweet plugin, I configured it on a local using.
 When I try it I received this message :
 
"Database query failed. Error received from database was 0001064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2014-02-25 16:12:46'', ''2014-02-25 16:12:46'')' at line 1 for the query: INSERT INTO mantis_plugin_ManTweet_updates_table ( author_id, status, date_submitted, date_updated ) VALUES (?, ?, ''2014-02-25 16:12:46'', ''2014-02-25 16:12:46'').
 "
 
Could somebody help me please.
Best regards.
 
Manu.

**Comment by luzpaz** [comment]
I'm pondering on using mantweet...is this issue still relevant?

**Comment by dregad** [comment]
This seems to be the same issue as 2nd bullet in #2.

I just did a quick check, and this error still exists in the current code base.
